events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name deploy.onyx.14082006.xyz gio.onyx.14082006.xyz victor.onyx.14082006.xyz marino.onyx.14082006.xyz jorge.onyx.14082006.xyz nicte.onyx.14082006.xyz;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name deploy.onyx.14082006.xyz;

        ssl_certificate /etc/letsencrypt/live/deploy.onyx.14082006.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/deploy.onyx.14082006.xyz/privkey.pem;

        location / {
            proxy_pass http://192.168.68.243:12000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 443 ssl;
        server_name gio.onyx.14082006.xyz;

        ssl_certificate /etc/letsencrypt/live/gio.onyx.14082006.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/gio.onyx.14082006.xyz/privkey.pem;

        location / {
            proxy_pass https://api_gio:12001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off;
        }
    }

    server {
        listen 443 ssl;
        server_name victor.onyx.14082006.xyz;

        ssl_certificate /etc/letsencrypt/live/victor.onyx.14082006.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/victor.onyx.14082006.xyz/privkey.pem;

        location / {
            proxy_pass https://api_victor:12002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off;
        }
    }

    server {
        listen 443 ssl;
        server_name marino.onyx.14082006.xyz;

        ssl_certificate /etc/letsencrypt/live/marino.onyx.14082006.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/marino.onyx.14082006.xyz/privkey.pem;

        location / {
            proxy_pass https://api_marino:12003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off;
        }
    }

    server {
        listen 443 ssl;
        server_name jorge.onyx.14082006.xyz;

        ssl_certificate /etc/letsencrypt/live/jorge.onyx.14082006.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/jorge.onyx.14082006.xyz/privkey.pem;

        location / {
            proxy_pass https://api_jorge:12004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off;
        }
    }

    server {
        listen 443 ssl;
        server_name nicte.onyx.14082006.xyz;

        ssl_certificate /etc/letsencrypt/live/nicte.onyx.14082006.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/nicte.onyx.14082006.xyz/privkey.pem;

        location / {
            proxy_pass https://api_nicte:12005;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off;
        }
    }
}